// src/app/layout.tsx
import type { Metadata } from "next";
import ClientProvider from "./components/ClientProvider";
import ClientLayout from "./components/ClientLayout";
import "./globals.css";

export const metadata: Metadata = {
  title: "Drone Access Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <ClientProvider>
          <ClientLayout>{children}</ClientLayout>
        </ClientProvider>
      </body>
    </html>
  );
}
